Refactor async order with quanto dimensions
Kwenta/synthetix-v3 pull request #12
Opened 2024-03-01 20:07 UTC by tommyrharper

2024-03-02 19:57 UTC, JaredBorders requested changes
Looking good, but there are some functions that haven't been touched yet (like `calculateFillPrice`, `calculateStartingPnl`, etc.). Not sure if there are reasons I am not across or if this is still a WIP. Lmk!

But great work!! 🔥

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/interfaces/IPerpsAccountModule.sol
>              uint256 requiredMaintenanceMargin,
`requiredMaintenanceMargin` is not unitless. Why only define `requiredInitialMargin` units?

(same for `maxLiquidationReward`)

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/modules/PerpsAccountModule.sol
> +    ) external view override returns (USDInt256 availableMargin) {
If this is always USD, but a trader is trading with ETH margin, how will the FE resolve this? Just ad hoc conversion?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/modules/PerpsAccountModule.sol
>      ) external view override returns (int256 withdrawableMargin) {
Why non-USD unit?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +    error InsufficientMargin(USDInt256 availableMargin, uint256 minMargin);
shouldn't `minMargin` be `USDInt256`?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +        if (order.request.sizeDelta.unwrap() != 0) {
why can't we have a `!=` User-Defined Operator?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +    // TODO: check to be sure commented out types can definitely be deleted safely
what needs to be done to confirm they can be safely removed?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/storage/AsyncOrder.sol
>          uint256 requiredMarginForNewPosition;
unitless?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/storage/AsyncOrder.sol
>          uint256 accumulatedLiquidationRewards;
unitless?

2024-03-02 19:57 UTC, JaredBorders commented on markets/perps-market/contracts/storage/AsyncOrder.sol
>          uint256 accumulatedLiquidationRewards;
Same for `requiredRewardMargin`

2024-03-04 20:59 UTC, tommyrharper commented on markets/perps-market/contracts/interfaces/IPerpsAccountModule.sol
>              uint256 requiredMaintenanceMargin,
will be fixed in future

2024-03-04 20:59 UTC, tommyrharper commented on markets/perps-market/contracts/modules/PerpsAccountModule.sol
>      ) external view override returns (int256 withdrawableMargin) {
non-comprehensive changes

2024-03-04 21:00 UTC, tommyrharper commented on markets/perps-market/contracts/modules/PerpsAccountModule.sol
> +    ) external view override returns (USDInt256 availableMargin) {
margin is in arbitrary assets, extra views can provide more granularity

2024-03-04 21:00 UTC, tommyrharper commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +        if (order.request.sizeDelta.unwrap() != 0) {
otherwise have to wrap 0

2024-03-04 21:00 UTC, tommyrharper commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +    error InsufficientMargin(USDInt256 availableMargin, uint256 minMargin);
non-comprehensive changes

2024-03-04 21:00 UTC, tommyrharper commented on markets/perps-market/contracts/storage/AsyncOrder.sol
>          uint256 requiredMarginForNewPosition;
non-comprehensive changes

2024-03-04 21:00 UTC, tommyrharper commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +    // TODO: check to be sure commented out types can definitely be deleted safely
im pretty sure they can be removed but will deal with later

2024-03-04 21:00 UTC, tommyrharper commented on markets/perps-market/contracts/storage/AsyncOrder.sol
>          uint256 accumulatedLiquidationRewards;
non-comprehensive changes

2024-03-04 21:01 UTC, merged