Extra type refactors
Kwenta/synthetix-v3 pull request #23
Opened 2024-04-02 13:04 UTC by tommyrharper

2024-04-03 22:10 UTC, JaredBorders requested changes

2024-04-04 14:31 UTC, tommyrharper commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +        BaseQuantoPerUSDInt256 pdAfter = newSkew.divDecimal(skewScale.toInt());
I have updated skewScale to be `BaseQuantoPerUSDUint256` and this fixes all of these issues perfectly.

2024-04-04 14:58 UTC, tommyrharper commented on markets/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol
> +        } else if (runtime.pnl.lessThanZero()) {
You think it's safe to just remove the check entirely? It feels a bit dodgy to me executing the logic when `pnl == 0`, but looking at the code it seems it will just go `runtime.amountToDeduct = runtime.amountToDeduct + 0` which should be fine 🤷

2024-04-04 15:01 UTC, tommyrharper commented on markets/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol
> +        } else if (runtime.pnl.lessThanZero()) {
Having said that, the counter argument to your point, is that while normally `pnl` will not equal zero, and hence it will be less gas efficient, in the case that it is zero, it will do a whole unnecessary query to an oracle to get the current quanto price, which will be expensive. Whereas a simple `pnl != 0` check should only cost 3 gas.

2024-04-04 15:41 UTC, JaredBorders approved these changes

2024-04-04 15:54 UTC, merged