Quanto units
Kwenta/synthetix-v3 pull request #3
Opened 2024-01-11 18:08 UTC by tommyrharper

A beautifully simple change to make quanto work.

2024-01-17 19:11 UTC, JaredBorders requested changes
I asked a couple of questions and made a suggestion or two. 

Overall, excellent work. This is a huge success in converting the system and probably the simplest way it could be done. 11/10

2024-01-17 19:11 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Quanto.test.ts
> +        const quantoPnl = bn(10_000).mul(2).mul(2); // $40k profit
same as earlier comment; lets write a helper func to do this for us

2024-01-17 19:11 UTC, JaredBorders commented on markets/perps-market/contracts/storage/PerpsAccount.sol
> +            // Note: getTotalCollateralValue already used this approach before i modified the code
I'm wondering if we should create an ETH:snxETH wrapper that is 1:1. Then if the wrapper exists, we can convert based on Oracle's price alone.

2024-01-18 11:30 UTC, tommyrharper commented on markets/perps-market/test/integration/Quanto/Quanto.test.ts
> +        bn(0.001), // quanto size = 10 eth * 3 leverage / 30,000 = 0.001
Done.

2024-01-18 14:05 UTC, tommyrharper commented on markets/perps-market/test/integration/Quanto/Quanto.test.ts
> +        .modifyCollateral(trader1AccountId, ethSpotMarketId, bn(10));
Done.

2024-01-18 14:12 UTC, tommyrharper commented on markets/perps-market/test/integration/Quanto/Quanto.test.ts
> +        const expectedOi = 60_000; // abs((-2 * 30000) + (20 * 2000))
I did think about adding a helper here, but I looked at the other tests and this situation and it just didn't make sense to abstract it. The comment is wrong though - so I just updated the comment to `// 2 BTC * 30k` because that is the calculation.

2024-01-18 14:17 UTC, tommyrharper commented on markets/perps-market/test/integration/Quanto/Quanto.test.ts
> +      it.skip('has correct margin based on classic perps price change', async () => {
done - good point

2024-01-18 14:17 UTC, tommyrharper commented on markets/perps-market/test/integration/Quanto/Quanto.test.ts
> +      it('has correct margin based on quanto perps price change', async () => {
🎉 woo!

2024-01-18 14:19 UTC, tommyrharper commented on markets/perps-market/contracts/modules/MarketConfigurationModule.sol
> +    ) external view returns (uint256) {
Done

2024-01-18 14:22 UTC, tommyrharper commented on markets/perps-market/contracts/storage/PerpsAccount.sol
> +    function convertAmountToUSD(int amount, uint128 synthMarketId, Price.Tolerance stalenessTolerance)
I have actually decided to change the approach to use an oracle directly. The perps market is no longer associated with a synth market, but instead just has two oracle feeds. I think the extra dependency on the spot market is a bad idea, because it creates a dependency for us on an external upgradeable contract. Much better to have more control ourselves. We can still use the same oracle as the synth market, but just link to it directly.

2024-01-18 14:37 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Quanto.test.ts
> +        const quantoPnl = bn(10_000).mul(2).mul(2); // $40k profit
Done.

2024-01-18 14:41 UTC, tommyrharper commented on markets/perps-market/contracts/storage/PerpsAccount.sol
> +            // Note: getTotalCollateralValue already used this approach before i modified the code
I agree that there should be such a wrapper, but I think it can go in a different PR. I believe we can use an oracle directly anyway, so I have actually removed this function.

2024-01-18 14:50 UTC, tommyrharper commented on markets/perps-market/contracts/modules/MarketConfigurationModule.sol
> +        PerpsMarketConfiguration.Data storage config = PerpsMarketConfiguration.load(marketId);
Actually that is a great question. I tested it - it silently succeeds 😯 - there is no reversion or error! You can actually set values on markets that don't exist. I guess it's not so bad because these are all only owner functions, but I am not sure it is ideal. I feel like this may be a design flaw in the snx system, and it would actually be wiser to update the `load` function to check if the market exists and revert if not. But this goes beyond a quanto change and into design decision for the v3 classic perps architecture, so perhaps best to hold off until we understand more the reasoning behind this decision. Does seem questionable.

2024-01-18 17:03 UTC, tommyrharper commented
@JaredBorders I am still making some large revisions to this code - so may not be worth looking too deeply into right now. Will let you know when it is ready for another review.

2024-01-30 17:20 UTC, merged