Position tests
Kwenta/synthetix-v3 pull request #9
Opened 2024-02-07 15:33 UTC by tommyrharper

2024-02-19 20:53 UTC, JaredBorders commented on markets/perps-market/contracts/storage/PerpsMarket.sol
> +                .mulDecimal(PerpsPrice.getCurrentQuantoPrice(marketId, PerpsPrice.Tolerance.DEFAULT))
it isn't necessarily our place, but maybe when we do make changes to these functions that have little or no documentation, we should add some ourselves. natspec for `requiredCredit` in this case.

2024-02-19 21:03 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +    const usdAmount = _BTC_PRICE.mul(trader2BTCMargin).div(ethers.utils.parseEther('1'));
instead of using `ethers.utils.parseEther('1')`, import `ONE_ETHER` from `Kwenta/synthetix-v3/markets/perps-market/test/integration/helpers/quanto.ts` and use it. 

Just cleans stuff up and is easier to read imo

2024-02-19 21:04 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +          quanto: {
It is interesting to see the BTC quanto market 👀

2024-02-19 21:06 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +      // END Classic QUANTO FUNDING CALC -------------------------------------------
remove "QUANTO"

2024-02-19 21:10 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +    const btcSpotMarketId = synthMarkets()[0].marketId();
repeating this line of code quite a bit. id define it with the others at the start

2024-02-19 21:10 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +      accountId: 2,
use constant you made

2024-02-19 21:11 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +            accountId: 3,
use constant

2024-02-19 21:11 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +            2,
use constant

2024-02-19 21:11 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +          const expectedAccruedFundingInUSD = expectedAccruedFunding.mul(20_000);
use _BTC_PRICE

2024-02-19 21:12 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +          assertBn.near(accruedFunding, expectedAccruedFunding.mul(-1).toBN(), bn(0.1));
why is this using "near"? was this how it was done before?

2024-02-19 21:12 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +          assertBn.near(accruedFunding, expectedAccruedFunding.mul(-1).toBN(), bn(0.1));
also, use constants

2024-02-19 21:14 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      2,
constant

2024-02-19 21:14 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      bn(1000)
constant

2024-02-19 21:15 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +    await systems().PerpsMarket.connect(trader1()).modifyCollateral(2, ethSpotMarketId, bn(25));
constant

2024-02-19 21:15 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +    await systems().PerpsMarket.connect(trader2()).modifyCollateral(3, ethSpotMarketId, bn(100));
constant

2024-02-19 21:16 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      assertBn.near(
another "near" use. I think answer to other q will resolve this too. but why "near"?

2024-02-19 21:16 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +        bn(0.0001)
constant

2024-02-19 21:16 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      assertBn.near(expectedUtilizationRate, utilRate.toBN(), bn(0.0001));
constant

2024-02-19 21:16 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      accountId: 2,
constant

2024-02-19 21:16 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +          2,
constant

2024-02-19 21:27 UTC, JaredBorders requested changes
I added quite a bit of comments & review comments. 

I think it will be more helpful in the future to outline in the PR noteworthy quanto specific changes happened in the test migrations. What I mean, is if the test is significantly different that what it is in the classic perps market tests. 

for example, 
"1. registered the quanto market"
"2. altered accrued interest calculation to include quanto price"

just helps the reviewer know "ok, this is new and needs deeper review!" Also makes it a bit easier for reviewer to focus on higher value changes

really great work on the migration!

2024-02-19 21:27 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +          2,
this is especially useful bc the 2 has been used prior for account id and this is a test for trader 1 interest

2024-02-19 21:27 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      before('trader2 changes OI', async () => {
trader2 but accountId 3 is used

2024-02-19 21:27 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      it('accrued correct interest for trader 1', async () => {
1 vs 2

2024-02-19 21:27 UTC, JaredBorders commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      it('accrued correct interest for trader 2', async () => {
2 vs 3

2024-02-26 15:16 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +    const usdAmount = _BTC_PRICE.mul(trader2BTCMargin).div(ethers.utils.parseEther('1'));
done.

2024-02-26 15:18 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +      // END Classic QUANTO FUNDING CALC -------------------------------------------
done

2024-02-26 15:21 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +      accountId: 2,
done

2024-02-26 15:21 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +            accountId: 3,
done

2024-02-26 15:22 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +            2,
done

2024-02-26 15:25 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/Funding.quanto.test.ts
> +          assertBn.near(accruedFunding, expectedAccruedFunding.mul(-1).toBN(), bn(0.1));
old tests also used near, i believe this is due to the time issues mentioned

2024-02-26 15:27 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      2,
done

2024-02-26 15:27 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      bn(1000)
done

2024-02-26 15:28 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +    await systems().PerpsMarket.connect(trader1()).modifyCollateral(2, ethSpotMarketId, bn(25));
done

2024-02-26 15:28 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +    await systems().PerpsMarket.connect(trader2()).modifyCollateral(3, ethSpotMarketId, bn(100));
done

2024-02-26 15:29 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      assertBn.near(
again, same issue described before

2024-02-26 15:31 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +        bn(0.0001)
done

2024-02-26 15:31 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      assertBn.near(expectedUtilizationRate, utilRate.toBN(), bn(0.0001));
done

2024-02-26 15:32 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +      accountId: 2,
done

2024-02-26 15:32 UTC, tommyrharper commented on markets/perps-market/test/quanto-integration/Position/InterestRate.quanto.test.ts
> +          2,
done

2024-02-26 15:35 UTC, merged